### PR TITLE
Merge castellanos70 f046e5c with ss013r 2421e72

### PR DESCRIPTION
**Pull request by max-sanchez**
Changes affect gamecards in the common package, as well as small modifications to starvationevasion.server.model.User, starvationevasion.sim.Model, and starvationevasion.sim.Simulator.

### CODE REVIEW

**Comment by kf4x** [comment]
@Ssagartz can you explain in this commit    e5460cf  why these are errors? I may be wrong but you are confusing
card

The actions are still the same see   `discard` method in [simulator](https://github.com/castellanos70/StarvationEvasion/blob/master/src/starvationevasion/sim/Simulator.java#L245)

During the draft phase a `User` can:
1. discard 
2. draw
3. draft

Actions in the handler are referring to draw, discard, draft. NOT anything to do with specifics of cards
**However** Like the documentation states a User can **discard** and **draw** at the same time which will give the user the ability to also draft. Still only add up to 2 total actions. I cannot find in the [spec](http://cs.unm.edu/~joel/cs351/worldFoodGame/CS-351-2015-Fall_StarvationEvasion_ProjectSpecifications.pdf) or in the [overview](http://cs.unm.edu/~joel/cs351/notes/CS-351-StarvationEvasion.pdf) wording that justify the changes that you are suggesting. @Ssagartz @ss013r @Vorksholk Please let me know if I am missing something!

**Comment by Ssagartz** [comment]
I'm not entirely sure of your question, but the idea behind this commit is to start using an action point system, where different cards have different action point costs, rather than just having two actions a turn.  The merge in question that you linked was to uncomment out the decrement to action points when a User discards, and switching actionsPointCost to the correct actionPointCost.  If the problem is with changing from actions to action Points, then we can revert, but the merge in question was just fixing spelling errors and using correct methods.

**Comment by kf4x** [comment]
@Ssagartz I just tested this and get errors and I get out of bounds errors because this allows the user to draft more cards into voting phase. 
I draft,  actions decrements to 2. I draft again and action decrements to 1. I was still able to draft and so I did. I got a index out of bounds.

**Comment by Ssagartz** [comment]
So I might know what is happening.  So the idea is that you may be able to draft more than one card a turn, due to the costs of some cards, but only one of them should be votable, since those cost 2 or more.  What I think may be happening is since we don't check whether you have enough points to play a card, rather, the check only sees if you have one or more, so you may have one point and use a card that costs two.  However, Im not sure how that would cause an out of bounds exception, but do you know what structure that error comes from?

**Comment by kf4x** [comment]
@Ssagartz its due to the ballot. it also needs to be revised. see [here](https://github.com/castellanos70/StarvationEvasion/blob/master/src/starvationevasion/server/Server.java#L535) and [here](https://github.com/castellanos70/StarvationEvasion/blob/master/src/starvationevasion/server/Server.java#L71)

**Comment by kf4x** [comment]
@Ssagartz or we need to make sure the action system that is being implemented still only allows two. My initial concern was I dont see where the total actions has chnaged.

**Comment by Ssagartz** [comment]
I think I understand now.  So you want a way that we can be sure that the user can only draft 1 or 2 cards?  That should be somewhat easy to fix by checking to see if the player has enough points, not just whether they have 1 or more.

**Comment by kf4x** [comment]
@Ssagartz yeah I think the card handler may need more checks, not just adding 3 actions to user

**Comment by Ssagartz** [comment]
Okay, I'll see what I can do.

**Comment by kf4x** [comment]
@Ssagartz Im just going to merge this in the mean time because this has lots of other changes that seem very useful. it only seems to happen if I am running a hard coded test case but I think my test cases would technically be illegal gameplay so sorry about that I think Ill have to revise my all my card tests to fit this new system. But I think there is a different bug that is causing errors in hands, which @jmccall2 had brought up in the past and now running into it again.

**Comment by Ssagartz** [comment]
I think the main confusion for me was in the method handleRequestImpl(), there are multiple checks for what sort of "action" is taking place, and I believe discarding used to be considered an action, and as such consumed one of the Users actionsRemaining.  However, when we thought about using a point system, we didn't think about having a cost associated with discarding at all, and I thought about just letting that happen without having it cost points, then I thought that if it originally had an inhibiting factor of costing an action, we should have it cost a point.

If I understood you correctly though, the error came in when the code enters the  "request.getDestination().equals(Endpoint.DRAFT_CARD)"

section.  I think with having a check that makes sure there are enough action points to play the card they wish to draft should be fine, since if we did our costing correctly, all the policy that require votes cost 2 or more, meaning that it should limit you to only using one of those per turn.  However, there may be an issue if they use a card that does not require voting multiple times, but I am still a bit unsure as to the error occuring, since I have an idea of what I think its doing along with a clear idea what I want it to do, but not a clear understanding of how the code handles the cards precisely.

If there is something that I can try to correct, I hope I can get to it sometime today, otherwise, thank you for helping me find the errors I caused.

**Comment by max-sanchez** [comment]
@javierchavez If you want to send me those tests once you're done revising, I can run them as part of my unit testing.

**Pull request merged**
